### ISSUE TITLE
Incompatible with PHPUnit 4.2.0

### ISSUE THREAD

**Issue by estahn** [michaelmoussa/doctrine-qbmocker#22]
``` bash
  Problem 1
    - Installation request for michaelmoussa/doctrine-qbmocker ^0.11.0 -> satisfiable by michaelmoussa/doctrine-qbmocker[0.11.0].
    - michaelmoussa/doctrine-qbmocker 0.11.0 requires phpunit/phpunit ^3.7.0 | ^4.2.0 -> no matching package found.
```

**Comment by michaelmoussa** [comment]
@estahn thanks for reporting this. Something must have gone astray with the `composer.lock` file on that last release. Please try [0.12.0](https://github.com/michaelmoussa/doctrine-qbmocker/releases/tag/0.12.0) and let me know if this solves your problem.
